-- Run this once in Supabase SQL Editor.
create table if not exists public.shops (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  city text not null,
  commission_per_item numeric not null default 0,
  minimum_order integer not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  shop_id uuid references public.shops(id) on delete cascade,
  owner_id uuid references auth.users(id) on delete cascade,
  name text not null,
  price numeric not null,
  stock integer not null default 0,
  minimum_order integer not null default 1,
  category text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  customer_name text not null,
  phone text not null,
  city text not null,
  address text not null,
  delivery_type text not null default 'standard',
  total numeric not null default 0,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.app_settings (
  id bigint generated by default as identity primary key,
  shop_creation boolean not null default true,
  product_addition boolean not null default true,
  customer_requests boolean not null default true,
  delivery boolean not null default true,
  commission boolean not null default true,
  minimum_order boolean not null default true,
  bulk_delivery_support boolean not null default true,
  bulk_order_minimum numeric not null default 100000,
  app_delivery_support_percent numeric not null default 50,
  shop_owner_registration boolean not null default true,
  customer_search boolean not null default true,
  quick_delivery boolean not null default true,
  quick_delivery_minutes integer not null default 30,
  quick_delivery_local_only boolean not null default true,
  other_delivery boolean not null default true,
  updated_at timestamptz not null default now()
);

insert into public.app_settings (id)
values (1)
on conflict (id) do nothing;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.shops enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.app_settings enable row level security;
alter table public.admin_users enable row level security;

drop policy if exists "public read shops" on public.shops;
create policy "public read shops" on public.shops for select using (true);

drop policy if exists "owners create shops" on public.shops;
create policy "owners create shops" on public.shops for insert to authenticated with check (owner_id = auth.uid());

drop policy if exists "public read products" on public.products;
create policy "public read products" on public.products for select using (true);

drop policy if exists "owners create products" on public.products;
create policy "owners create products" on public.products for insert to authenticated with check (owner_id = auth.uid());

drop policy if exists "users create orders" on public.orders;
create policy "users create orders" on public.orders for insert to authenticated with check (user_id = auth.uid());

drop policy if exists "users read own orders" on public.orders;
create policy "users read own orders" on public.orders for select to authenticated using (user_id = auth.uid());

drop policy if exists "public read settings" on public.app_settings;
create policy "public read settings" on public.app_settings for select using (true);

drop policy if exists "admins update settings" on public.app_settings;
create policy "admins update settings" on public.app_settings for update to authenticated
using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()))
with check (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));

drop policy if exists "admins read own record" on public.admin_users;
create policy "admins read own record" on public.admin_users for select to authenticated using (user_id = auth.uid());

-- After creating the admin account in Supabase Auth, run:
-- insert into public.admin_users(user_id) values ('YOUR-ADMIN-USER-UUID');
