-- Quick Marketplace 4.0 migration for the existing database.
-- orders.id is BIGINT, so delivery/order item references use BIGINT.
alter table public.shops add column if not exists commission_per_item numeric not null default 0;
alter table public.shops add column if not exists minimum_order_quantity integer not null default 1;
alter table public.products add column if not exists category text not null default 'Other';
alter table public.products add column if not exists description text;
alter table public.products add column if not exists image_url text;
alter table public.products add column if not exists stock integer not null default 0;
alter table public.products add column if not exists is_available boolean not null default true;
alter table public.order_items add column if not exists order_id bigint;
alter table public.order_items add column if not exists product_id bigint;
alter table public.order_items add column if not exists quantity integer not null default 1;
alter table public.order_items add column if not exists unit_price numeric not null default 0;
alter table public.order_items add column if not exists total_price numeric not null default 0;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text,phone text,role text not null default 'customer',city text,address text,created_at timestamptz not null default now());
create table if not exists public.delivery_routes(id bigint generated by default as identity primary key,from_city text not null,to_city text not null,estimated_days integer not null default 1,delivery_fee numeric not null default 0,is_active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.delivery_assignments(id bigint generated by default as identity primary key,order_id bigint not null references public.orders(id) on delete cascade,delivery_person_id uuid references public.profiles(id) on delete set null,status text not null default 'pending',assigned_at timestamptz,completed_at timestamptz,created_at timestamptz not null default now());
alter table public.app_settings add column if not exists quick_delivery boolean not null default true;
alter table public.app_settings add column if not exists quick_delivery_minutes integer not null default 30;
alter table public.app_settings add column if not exists quick_delivery_local_only boolean not null default true;
alter table public.app_settings add column if not exists other_delivery boolean not null default true;
create index if not exists products_shop_id_idx on public.products(shop_id);
create index if not exists orders_customer_id_idx on public.orders(customer_id);
create index if not exists delivery_assignments_order_id_idx on public.delivery_assignments(order_id);
create index if not exists delivery_routes_from_to_idx on public.delivery_routes(from_city,to_city);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,full_name,role) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''),coalesce(new.raw_user_meta_data->>'role','customer')) on conflict(id) do update set full_name=excluded.full_name; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
-- Keep your existing RLS policies. Do not disable RLS. Delivery assignments should allow delivery users to read their own assignments.
