-- Quick Marketplace 4.0 migration for the existing database.
-- orders.id is BIGINT, so delivery/order item references use BIGINT.
alter table public.shops add column if not exists commission_per_item numeric not null default 0;
alter table public.shops add column if not exists minimum_order_quantity integer not null default 1;
alter table public.products add column if not exists category text not null default 'Other';
alter table public.products add column if not exists description text;
alter table public.products add column if not exists image_url text;
alter table public.products add column if not exists stock integer not null default 0;
alter table public.products add column if not exists is_available boolean not null default true;
alter table public.order_items add column if not exists order_id bigint;
alter table public.order_items add column if not exists product_id bigint;
alter table public.order_items add column if not exists quantity integer not null default 1;
alter table public.order_items add column if not exists unit_price numeric not null default 0;
alter table public.order_items add column if not exists total_price numeric not null default 0;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text,phone text,role text not null default 'customer',city text,address text,created_at timestamptz not null default now());
create table if not exists public.delivery_routes(id bigint generated by default as identity primary key,from_city text not null,to_city text not null,estimated_days integer not null default 1,delivery_fee numeric not null default 0,is_active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.delivery_assignments(id bigint generated by default as identity primary key,order_id bigint not null references public.orders(id) on delete cascade,delivery_person_id uuid references public.profiles(id) on delete set null,status text not null default 'pending',assigned_at timestamptz,completed_at timestamptz,created_at timestamptz not null default now());
alter table public.app_settings add column if not exists quick_delivery boolean not null default true;
alter table public.app_settings add column if not exists quick_delivery_minutes integer not null default 30;
alter table public.app_settings add column if not exists quick_delivery_local_only boolean not null default true;
alter table public.app_settings add column if not exists other_delivery boolean not null default true;
create index if not exists products_shop_id_idx on public.products(shop_id);
create index if not exists orders_customer_id_idx on public.orders(customer_id);
create index if not exists delivery_assignments_order_id_idx on public.delivery_assignments(order_id);
create index if not exists delivery_routes_from_to_idx on public.delivery_routes(from_city,to_city);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,full_name,role) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''),coalesce(new.raw_user_meta_data->>'role','customer')) on conflict(id) do update set full_name=excluded.full_name; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
-- Keep your existing RLS policies. Do not disable RLS. Delivery assignments should allow delivery users to read their own assignments.

-- ===== Quick Marketplace RLS / reliability patch =====

alter table public.profiles enable row level security;
alter table public.shops enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.delivery_routes enable row level security;
alter table public.delivery_assignments enable row level security;
alter table public.app_settings enable row level security;

-- Profiles
 drop policy if exists "qm_profiles_select_own" on public.profiles;
create policy "qm_profiles_select_own" on public.profiles for select to authenticated using (id = auth.uid());
drop policy if exists "qm_profiles_update_own" on public.profiles;
create policy "qm_profiles_update_own" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

-- Shops: public marketplace visibility, owner management
 drop policy if exists "qm_shops_public_read" on public.shops;
create policy "qm_shops_public_read" on public.shops for select using (true);
drop policy if exists "qm_shops_owner_insert" on public.shops;
create policy "qm_shops_owner_insert" on public.shops for insert to authenticated with check (owner_id = auth.uid());
drop policy if exists "qm_shops_owner_update" on public.shops;
create policy "qm_shops_owner_update" on public.shops for update to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
drop policy if exists "qm_shops_owner_delete" on public.shops;
create policy "qm_shops_owner_delete" on public.shops for delete to authenticated using (owner_id = auth.uid());

-- Products: public read, shop owner writes
 drop policy if exists "qm_products_public_read" on public.products;
create policy "qm_products_public_read" on public.products for select using (true);
drop policy if exists "qm_products_owner_insert" on public.products;
create policy "qm_products_owner_insert" on public.products for insert to authenticated with check (exists (select 1 from public.shops s where s.id = shop_id and s.owner_id = auth.uid()));
drop policy if exists "qm_products_owner_update" on public.products;
create policy "qm_products_owner_update" on public.products for update to authenticated using (exists (select 1 from public.shops s where s.id = shop_id and s.owner_id = auth.uid())) with check (exists (select 1 from public.shops s where s.id = shop_id and s.owner_id = auth.uid()));
drop policy if exists "qm_products_owner_delete" on public.products;
create policy "qm_products_owner_delete" on public.products for delete to authenticated using (exists (select 1 from public.shops s where s.id = shop_id and s.owner_id = auth.uid()));

-- Orders: customers create/read their own; shop owners/admins can read related orders.
drop policy if exists "qm_orders_customer_insert" on public.orders;
create policy "qm_orders_customer_insert" on public.orders for insert to authenticated with check (customer_id = auth.uid());
drop policy if exists "qm_orders_read_related" on public.orders;
create policy "qm_orders_read_related" on public.orders for select to authenticated using (
  customer_id = auth.uid()
  or exists (select 1 from public.shops s where s.id = shop_id and s.owner_id = auth.uid())
  or exists (select 1 from public.admin_users a where a.user_id = auth.uid())
  or exists (select 1 from public.delivery_assignments da where da.order_id = orders.id and da.delivery_person_id = auth.uid())
);

-- Order items: access follows the parent order.
drop policy if exists "qm_order_items_read" on public.order_items;
create policy "qm_order_items_read" on public.order_items for select to authenticated using (
  exists (select 1 from public.orders o where o.id = order_id and (
    o.customer_id = auth.uid()
    or exists (select 1 from public.shops s where s.id = o.shop_id and s.owner_id = auth.uid())
    or exists (select 1 from public.admin_users a where a.user_id = auth.uid())
  ))
);
drop policy if exists "qm_order_items_customer_insert" on public.order_items;
create policy "qm_order_items_customer_insert" on public.order_items for insert to authenticated with check (
  exists (select 1 from public.orders o where o.id = order_id and o.customer_id = auth.uid())
);

-- Delivery routes: everyone can read active routes; admins manage.
drop policy if exists "qm_routes_public_read" on public.delivery_routes;
create policy "qm_routes_public_read" on public.delivery_routes for select using (is_active = true or exists (select 1 from public.admin_users a where a.user_id = auth.uid()));
drop policy if exists "qm_routes_admin_insert" on public.delivery_routes;
create policy "qm_routes_admin_insert" on public.delivery_routes for insert to authenticated with check (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));
drop policy if exists "qm_routes_admin_update" on public.delivery_routes;
create policy "qm_routes_admin_update" on public.delivery_routes for update to authenticated using (exists (select 1 from public.admin_users a where a.user_id = auth.uid())) with check (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));
drop policy if exists "qm_routes_admin_delete" on public.delivery_routes;
create policy "qm_routes_admin_delete" on public.delivery_routes for delete to authenticated using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));

-- Delivery assignments: delivery workers see/update their own jobs; admins manage all.
drop policy if exists "qm_delivery_read" on public.delivery_assignments;
create policy "qm_delivery_read" on public.delivery_assignments for select to authenticated using (
  delivery_person_id = auth.uid()
  or exists (select 1 from public.admin_users a where a.user_id = auth.uid())
);
drop policy if exists "qm_delivery_update" on public.delivery_assignments;
create policy "qm_delivery_update" on public.delivery_assignments for update to authenticated using (
  delivery_person_id = auth.uid()
  or exists (select 1 from public.admin_users a where a.user_id = auth.uid())
) with check (
  delivery_person_id = auth.uid()
  or exists (select 1 from public.admin_users a where a.user_id = auth.uid())
);

-- App settings: marketplace settings are readable; only admins can change them.
drop policy if exists "qm_settings_public_read" on public.app_settings;
create policy "qm_settings_public_read" on public.app_settings for select using (true);
drop policy if exists "qm_settings_admin_update" on public.app_settings;
create policy "qm_settings_admin_update" on public.app_settings for update to authenticated using (exists (select 1 from public.admin_users a where a.user_id = auth.uid())) with check (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));

-- Create an empty delivery assignment automatically for every new order.
-- This is SECURITY DEFINER so the customer does not need INSERT permission on delivery_assignments.
create or replace function public.qm_create_delivery_assignment()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.delivery_assignments(order_id, status)
  values (new.id, 'pending');
  return new;
end;
$$;

drop trigger if exists qm_order_delivery_assignment on public.orders;
create trigger qm_order_delivery_assignment
after insert on public.orders
for each row execute function public.qm_create_delivery_assignment();

